name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
      id: go
    
    - name: Get gopherjs
      run: go get github.com/gopherjs/gopherjs

    - name: Install gopherjs
      run: go install github.com/gopherjs/gopherjs
    
    - name: Go get
      run: go get github.com/mark07x/YanBiaoJiuMing
            
    - name: Build
      run: gopherjs build -m github.com/mark07x/YanBiaoJiuMing
    
    - name: Gen dummy page
      run: |
        ls
        pwd
        cat > index.md <<EOL
        ## YanBiaoJiuMing Online
        <p>
        <input class="content" placeholder="Content">
        </p>
        <p>
        <input class="seed" placeholder="Seed">
        </p>
        <p>
        <input class="size" placeholder="Size">
        </p>
        <p>
        <button class="shuffle">Shuffle</button>
        </p>
        <input class="result">
        <p>
        <script src="YanBiaoJiuMing.js"></script>
        </p>
        EOL
        cat > _config.yml <<EOL
        ## YanBiaoJiuMing Online
        theme: jekyll-theme-cayman
        EOL
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: gh-pages
        build_dir: .
