name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
      id: go
    
    - name: Get gopherjs
      run: go get github.com/gopherjs/gopherjs

    - name: Install gopherjs
      run: go install github.com/gopherjs/gopherjs
    
    - name: Gopherjs get
      run: gopherjs get github.com/mark07x/YanBiaoJiuMing
            
    - name: Build
      run: gopherjs build -m github.com/mark07x/YanBiaoJiuMing
    
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if:
        startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: true
        files: 
          ./YanBiaoJiuMing.js
          ./YanBiaoJiuMing.js.map
